services:

  app:
    image: 'coupon-management-system:latest'
    networks:
      - data
    build:
      context: ./backend
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/coupon
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - '8080:8080'

  postgres:
    image: 'postgres:latest'
    networks:
      - data
    environment:
      - POSTGRES_DB=coupon
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    
networks:
  data:
